name: Run Unit Tests
"on": [ workflow_dispatch ]
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up node 
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run tests 
        run: npm test:unit

      - name: Run lint 
        run: npm lint